### ISSUE TITLE
Loading failed in the search bar when trying to invite user (504 error on the underlying HTTP GET request)

### ISSUE THREAD

**Issue by lesteve** [hackmdio/hackmd-io-issues#127]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io

### Read our Official tutorial

It's on https://hackmd.io/c/tutorials/

### What's the problem

I am trying to invite people to a note following: https://hackmd.io/c/tutorials/%2Fs%2Finvite. When searching for a user name, I am not able to find any user and it says "Loading Failed" after some time (30 seconds roughly).

#### Current behaviour

> Screenshot (optional)

![image](https://user-images.githubusercontent.com/1680079/68310828-f30a3d00-00b0-11ea-8770-e27ce609671c.png)

Provide steps to reproduce:

1. Try to invite someone to a note following https://hackmd.io/c/tutorials/%2Fs%2Finvite
2. Type `lfa` in the search bar
3. below the search bar "Searching" is shown for a long time (with the wheel turning) and then "Loading failed" eventually

I can reproduce from this note:
https://hackmd.io/hsjixoPNQV6mHO1Sp35lsw

Looking at the developer tools, I can see that the HTTP GET request is `https://hackmd.io/searchUser?q=lfa` and gets a 504 (Gateway Timeout).

#### Expected behaviour

I can find the user names I am looking for and eventually can invite them.

#### Environment

I use HackMD on:

**Desktop**
- OS: Ubuntu 16.04
- Browser: Firefox and Chromium
- Browser Version: Firefox 69.0.1, Chromium 77.0.3865.90

**Comment by jackycute** [comment]
Hi @lesteve,
Thanks for reporting to us.
We currently are trying our best to solve this issue, it will take more time.

**Comment by lesteve** [comment]
Thanks a lot for your answer! Let me know when you think you have a fix for this, I'll be happy to double-check!

**Comment by jackycute** [comment]
@lesteve We've fixed this issue, could you please check?

**Comment by lesteve** [comment]
I am not getting "Loading failed" anymore. I still have trouble to find users though: for example if I search you username, I can not find it:
![image](https://user-images.githubusercontent.com/1680079/68367034-fe9f4780-0134-11ea-8ca7-d0cc2741a41a.png)

I used the same note mentionned in my original post: https://hackmd.io/hsjixoPNQV6mHO1Sp35lsw (although I am guessing which note you use does not really matter)

**Comment by jackycute** [comment]
> I am not getting "Loading failed" anymore. I still have trouble to find users though: for example if I search you username, I can not find it:
> ![image](https://user-images.githubusercontent.com/1680079/68367034-fe9f4780-0134-11ea-8ca7-d0cc2741a41a.png)
> 
> I used the same note mentionned in my original post: [hackmd.io/hsjixoPNQV6mHO1Sp35lsw](https://hackmd.io/hsjixoPNQV6mHO1Sp35lsw) (although I am guessing which note you use does not really matter)

My username is `MaxWu`: https://hackmd.io/@MaxWu

**Comment by lesteve** [comment]
I see, I naively thought I could find users by github name (I am using hackmd.io coming from a github context and I logged into hackmd.io using github authentication). It did not occur to me there were hackmd.io user names. Maybe being more explicit about using "hackmd.io username" could be specified in: https://hackmd.io/c/tutorials/%2Fs%2Finvite. A tiny thing is that the search bar has a text (before you type anything) saying "search user by email ..." maybe it "or hackmd.io user name" could be added (if it fits ...). 

Below are another few nice things to have (in an ideal world, I completely understand you may have higher priorities). Not sure how hard they are technically (probably not that straightforward) and whether some are easier than others:
- search by github (Twitter, or other auth types) names. By the way, I am not sure what username I get when I sign in with github. Maybe you should keep the github username (e.g. lesteve) rather than my full name (e.g. Loïc Estève)
- more flexible search: if I type "grisel" in the search bar I should be able to find "Olivier Grisel" and I am not (see screenshots below)
![image](https://user-images.githubusercontent.com/1680079/68378945-45993700-014d-11ea-8d63-60a926d2655c.png)

![image](https://user-images.githubusercontent.com/1680079/68378988-5649ad00-014d-11ea-9b19-17bb462e6fee.png)

Anyway thanks a lot for the quick fix of the original issue! I am more than happy to move this discussion to a separate issue if you prefer!

**Comment by lesteve** [comment]
I am going to close this issue since the original problem was fixed (thanks a lot for the quick fix!). I opened #129 for possible search enhancements.

**Comment by wgshtg** [comment]
The problem still existed.
![image](https://user-images.githubusercontent.com/25994242/69008564-b67af300-0986-11ea-8fb5-fc3b37fe8d9b.png)
![image](https://user-images.githubusercontent.com/25994242/69008606-36a15880-0987-11ea-8ec7-7eb42aea7b96.png)
![image](https://user-images.githubusercontent.com/25994242/69008586-00fc6f80-0987-11ea-9486-36cbb339e132.png)
I can't invite anyone. Please help me and thanks.
